In [52]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import prody_ as pr
#Parameters
#sequence="GLY"
sequence="SER"
#temp=[298]
#temp=[328]
#temp=[358]
temp=[400]
#temp=[298, 328, 358]
#temp=[298, 328, 358, 400]
wb=True
wb=False

n=100n

pr.getstartingpdb(sequence,temp,wb,n)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

@> 23 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> 23 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> 23 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> 23 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> 23 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> 23 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> 23 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> 23 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> 23 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> 23 atoms and 1 coordinate set(s) were parsed in 0.00s.

works
f8a48599-c9a8-475a-9d1a-29b9f737bf57
ade46d77-35b1-42c8-9161-f27295065131
f0001e2d-86cc-4d85-bf71-6972284320e0
af774bbc-cfe5-4bc7-a21e-c5d00cd112ba
af774bbc-cfe5-4bc7-a21e-c5d00cd112ba
8653530a-c915-4418-858a-7f1758216d37
af774bbc-cfe5-4bc7-a21e-c5d00cd112ba
3f075a54-daa9-4379-af75-44e9ff2e2075
7b88e64c-5deb-45bd-bf00-7a4c05979dcf
f0001e2d-86cc-4d85-bf71-6972284320e0

,sequence,key,phi,psi,omega,e2e,rgyr
3886,ser,f8a48599-c9a8-475a-9d1a-29b9f737bf57,-176.970978,-171.748932,-165.522858,5.923987,2.976137
3724,ser,ade46d77-35b1-42c8-9161-f27295065131,-156.609756,152.481537,177.118744,5.808939,2.950720
359,ser,f0001e2d-86cc-4d85-bf71-6972284320e0,-176.509003,168.676544,-175.586685,6.034700,2.937830
3024,ser,af774bbc-cfe5-4bc7-a21e-c5d00cd112ba,-160.007553,-165.422089,175.760147,5.841827,2.975346
2121,ser,af774bbc-cfe5-4bc7-a21e-c5d00cd112ba,-80.681664,64.846870,177.525116,4.560262,2.822163
2419,ser,8653530a-c915-4418-858a-7f1758216d37,-170.244751,-145.497116,170.698898,5.742315,2.924001
539,ser,af774bbc-cfe5-4bc7-a21e-c5d00cd112ba,-147.382401,170.906845,-169.885468,6.018034,2.995335
1886,ser,3f075a54-daa9-4379-af75-44e9ff2e2075,-176.442795,-160.485474,-179.595932,6.100926,2.983269
4150,ser,7b88e64c-5deb-45bd-bf00-7a4c05979dcf,-165.058777,-169.418808,-170.327484,5.956019,2.950524
2181,ser,f0001e2d-86cc-4d85-bf71-6972284320e0,-137.675964,-167.785324,-167.804916,6.060439,2.949746